#!/bin/sh
set -eu

base_url="https://m3u8-player.net"
command="${1:-home}"
value="${2:-}"

case "$command" in
  home)
    printf '%s\n' "$base_url"
    ;;
  tool)
    clean=$(printf '%s' "$value" | sed 's#^/*##; s#/*$##')
    if [ -z "$clean" ]; then
      printf '%s\n' "$base_url"
    else
      printf '%s/%s/\n' "$base_url" "$clean"
    fi
    ;;
  player)
    printf '%s/#player\n' "$base_url"
    ;;
  downloader)
    printf '%s/m3u8downloader/\n' "$base_url"
    ;;
  converter)
    printf '%s/m3u8tomp4/\n' "$base_url"
    ;;
  hls)
    printf '%s/hls-player/\n' "$base_url"
    ;;
  *)
    printf 'usage: m3u8-player-site-kit [home|player|downloader|converter|hls|tool <slug>]\n' >&2
    exit 64
    ;;
esac
